baseURL: 'https://www.marku.me/'
languageCode: 'es'
title: 'Marku blog'
authors:
  - name: Ricardo Martin Marcucci
theme: 'marku'
enableEmoji: true
paginate: 5

enableGitInfo: true
taxonomies:
  category: 'categories'
  tag: 'tags'
  series: 'series'

outputs:
  home:
    - 'HTML'
    - 'RSS'
    - 'JSON'

defaultContentLanguage: 'es'
languages:
  en:
    languageName: 'English'
    languageCode: 'en'
    weight: 1
    params:
      languageFlag: 'ðŸ‡¬ðŸ‡§'

  es:
    languageName: 'EspaÃ±ol'
    languageCode: 'es'
    weight: 2
    params:
      languageFlag: 'ðŸ‡ªðŸ‡¸'

params:
  description: Between transistors and bytes
  images:
    - site-feature-image.jpg
  title: 'Marku blog'
  tags: true
